/** R3-L0A effects module type declarations (harness-only). */
export declare const STAGE_EVIDENCE_PATH: string;
export declare const EXPOSURE_SIGNATURES: Readonly<Record<string, readonly string[]>>;
export declare const EXPOSURE_CLASSES: Readonly<Record<string, readonly string[]>>;
export declare function decompressFrames(path: string): string;
export declare function sessionArtifacts(home: string): readonly any[];
export declare function sessionRecords(text: string): readonly any[];
export declare function reconstructPath(artifact: any): any;
export declare function reconstructTrajectory(home: string): readonly any[];
export declare const AMENDED_PLAN_COMMIT: string;
export declare const DESIGN_COMMIT: string;
export declare const RESULT_COMMIT: string;
export declare const CHANGE_CLASSES: Readonly<Record<string, string>>;
export declare function recoverPreAmendCommit(): any;
export declare function planAmendmentDiff(preAmendSha: string | null, amendedSha?: string): any;
export declare function immutabilityLaw(): any;
export declare function protocolErratum(preAmend: any): any;
export declare const NOVELTY_LABELS: Readonly<Record<string, string>>;
export declare const SEMANTIC_PROBES: Readonly<Record<string, any>>;
export declare function ordinarySurfaces(): readonly any[];
export declare function auditLesson(lessonId: string): any;
export declare function effectLayers(): readonly any[];
export declare function causalStatus(adjudication: any): any;
export declare function designLaw(): any;
export declare function recommendation(adjudication: any, novelty: readonly any[]): any;
export declare function genericPriorLimitation(): any;
export declare const STATE_FILES: readonly string[];
export declare const WORLD_FILES: readonly string[];
export declare const KNOWLEDGE_FILES: readonly string[];
export declare function treatmentDelta(runDir: string): any;
export declare function informationPaths(runDir: string, matrix: any): any;
export declare function historyAccessSummary(pathsByTrajectory: any): any;
export declare function capitalPathSummary(pathsByTrajectory: any): any;
export declare function matchedHistoryUse(pathsByTrajectory: any, matrix: any): any;
export declare function costDecomposition(matrix: any): any;
export declare function capitalOverhead(matrix: any, pathsByTrajectory: any): any;
export declare function forensicB0CG3(matrix: any, pathsByTrajectory: any): any;
