/** R3-L0C contract module type declarations (harness-only, research infrastructure). */
export declare const REPO_ROOT: string;
export declare const STAGE_EVIDENCE_PATH: string;
export declare const VALIDITY_PREREQUISITES: any;
export declare const PREFLIGHT_REPAIRS: readonly any[];
export declare const PREFLIGHT_GATE: string;
export declare const PROJECT: any;
export declare const INVARIANTS: readonly any[];
export declare const INVARIANT_IDS: readonly string[];
export declare const CORPUS_CATEGORIES: readonly any[];
export declare const CORPUS_DIFFICULTY: any;
export declare const ARMS: { readonly H: any; readonly C: any };
export declare const TREATMENT: any;
export declare const BLOCK_COUNT: number;
export declare const GENERATIONS_PER_TRAJECTORY: number;
export declare const SESSIONS_PER_BLOCK: number;
export declare const TOTAL_SESSIONS: number;
export declare const RANDOMIZATION_SEED: number;
export declare const GENERATIONS: readonly any[];
export declare function generationOf(id: string): any;
export declare const RUN_BUDGET: any;
export declare const OUTCOME_SCHEMA: any;
export declare const RECONSTRUCTION_COST_RULES: any;
export declare const COMPLETION_CAUSES: Readonly<Record<string, string>>;
export declare const INFORMATION_PATHS: Readonly<Record<string, string>>;
export declare const PATH_CLASSIFICATION_LAW: string;
export declare const COMPRESSION_VERDICT_RULES: any;
export declare const NET_COST_VERDICT_RULES: any;
export declare const CORRECTNESS_INTERPRETATION: any;
export declare const CONTRAST: any;
export declare const STAGE_LAWS: Readonly<Record<string, string>>;
export declare const INTERPRETATION_SCOPE: any;
export declare const NEXT_GATE_RULES: Readonly<Record<string, any>>;
export declare const FINAL_VERDICTS: any;
export declare const COMMIT_STRUCTURE: readonly string[];
export declare function contractSummary(): any;
