/**
 * R3-L0C §5/§6 — THE FROZEN RAW PROJECT HISTORY CORPUS.
 *
 * §5 requires a realistic deterministic corpus containing incident records, decision/revision records, current
 * and superseded rules, verification/results, migration/compatibility notes, and ordinary irrelevant-but-plausible
 * history. §5 also fixes the DIFFICULTY and its limits, and both are load-bearing:
 *
 *   the difficulty is  SEARCH + CHRONOLOGY + STANDING RECONSTRUCTION
 *   it is NOT           ALGORITHMIC OBSCURITY
 *   and it must NOT     bury the answer behind intentionally misleading noise
 *
 * So the corpus is LARGE and the answer is RECOVERABLE. Nothing here lies: a superseded document says so, in
 * its own text. What makes the work real is that the worker must FIND the relevant records among plausible
 * neighbours, ORDER them by date, and DERIVE the current standing — because the newest document is not always
 * the one that decides, and the rule that decides is not the rule that was written first.
 *
 * THE CORPUS IS SUFFICIENT. §5 requires that a diligent worker can reconstruct the correct current standing
 * from raw history alone, because otherwise the H arm would measure oracle access rather than reconstruction.
 * Every fact needed to derive I1 and I2 is present, in the form the Project actually recorded it.
 *
 * PLAIN JAVASCRIPT (`.mjs`).
 */
import { CORPUS_CATEGORIES } from './contract.mjs';

const NL = String.fromCharCode(10);

/** §5: the corpus root inside the Project world. */
export const CORPUS_ROOT = 'docs/history';

/**
 * §5: THE DOCUMENTS.
 *
 * `standing` is the classification a reader must arrive at, and it is recorded here for AUDIT rather than for
 * the worker: the corpus files themselves carry no such field, and a worker must infer it from the text. The
 * distinction matters because a test asserts that the recorded classification is DERIVABLE from the document
 * text alone, which is what keeps the corpus honest rather than cryptic.
 */
export const CORPUS_DOCUMENTS = Object.freeze([
  /* ============================================================ the I1 lineage */

  Object.freeze({
    id: 'INC-0007', category: 'INCIDENT', path: `${CORPUS_ROOT}/incidents/0007-legacy-deny-overturned.md`,
    date: '2023-11-14', standing: 'CURRENT',
    title: 'INC-0007 — a legacy deny was silently overturned by an inherited allow',
    body: [
      '# INC-0007 — a legacy deny was silently overturned by an inherited allow',
      '',
      '**Date:** 2023-11-14  **Severity:** high  **Status:** resolved',
      '',
      '## What happened',
      '',
      'Tenant `northwind` had been explicitly denied the `ledger.approve` capability in 2022, under the legacy',
      'policy engine. During the new engine pilot, an ALLOW was inherited into `northwind` from a parent',
      'entitlement group. The service reported the tenant as ALLOWED, and an operator approved a payment run the',
      'deny was recorded to prevent.',
      '',
      '## Why it happened',
      '',
      'The new engine evaluates from its own policy set. It has no representation of a decision the legacy engine',
      'recorded, so an inherited ALLOW was not compared against the existing legacy DENY at all. The two engines',
      'each answered correctly about their own inputs, and nobody compared the answers.',
      '',
      '## Resolution',
      '',
      'A DENY recorded by the legacy engine is FINAL for the tenant it was recorded against. A later ALLOW must',
      'not overturn it. This was implemented as a precedence rule, not as a data migration, because migrating the',
      'legacy denials would have lost the fact that they were recorded by the other engine.',
      '',
      '## Follow-up',
      '',
      'DEC-0031 records the decision. REV-0004 records the rule revision.',
      '',
    ].join(NL),
  }),

  Object.freeze({
    id: 'DEC-0031', category: 'DECISION', path: `${CORPUS_ROOT}/decisions/0031-legacy-deny-is-final.md`,
    date: '2023-11-21', standing: 'SUPERSEDED_IN_PART',
    title: 'DEC-0031 — a legacy DENY is final',
    body: [
      '# DEC-0031 — a legacy DENY is final',
      '',
      '**Date:** 2023-11-21  **Status:** accepted  **Superseded in part by:** DEC-0044, REV-0009',
      '',
      '## Decision',
      '',
      'A DENY recorded by the legacy policy engine is final for the tenant it was recorded against. No later',
      'ALLOW, from any source, overturns it.',
      '',
      '## Context',
      '',
      'Following INC-0007. The alternative considered was to migrate every legacy denial into the new engine, so',
      'that ordinary evaluation would handle it. That was rejected because the migration would have destroyed the',
      'provenance: after migration, an operator could no longer tell which engine had recorded the denial, and the',
      'audit trail for the 2022 approvals depended on that distinction.',
      '',
      '## Consequences',
      '',
      '- the precedence rule lives in the resolver, not in the stored decisions;',
      '- every stored decision keeps its `source` field, which must never be rewritten;',
      '- **this rule applies to every tenant**, because at the time of this decision there was no other kind.',
      '',
      '## Note for readers',
      '',
      'The scope sentence above was correct in 2023. It is no longer the whole rule — see DEC-0044 for the',
      'post-cutover tenant class, and REV-0009 for the date that actually decides.',
      '',
    ].join(NL),
  }),

  Object.freeze({
    id: 'REV-0004', category: 'REVISION', path: `${CORPUS_ROOT}/revisions/0004-legacy-deny-final-implemented.md`,
    date: '2023-12-05', standing: 'SUPERSEDED_IN_PART',
    title: 'REV-0004 — precedence rule implemented in the resolver',
    body: [
      '# REV-0004 — precedence rule implemented in the resolver',
      '',
      '**Date:** 2023-12-05  **Supersedes:** nothing  **Status:** superseded in part by REV-0009',
      '',
      '## Change',
      '',
      'The resolver now consults the legacy-finality rule before returning a decision. When a legacy DENY exists',
      'for the tenant and capability, the resolver returns DENY regardless of any newer ALLOW.',
      '',
      '## Verification',
      '',
      'VER-0012 covers this change and passed: for a tenant with a legacy DENY and a newer ALLOW, the resolver',
      'returns DENY.',
      '',
      '## Known limitation, recorded at the time',
      '',
      'The rule was written for a world in which every tenant had been evaluated by the legacy engine. When the',
      'new engine began onboarding tenants that had NEVER had a legacy decision, the rule was still applied, and a',
      'new tenant with no legacy history was unaffected — but the case where a new tenant INHERITS a deny from a',
      'parent group was not considered and is handled by DEC-0044.',
      '',
    ].join(NL),
  }),

  Object.freeze({
    id: 'VER-0012', category: 'VERIFICATION', path: `${CORPUS_ROOT}/verification/0012-legacy-finality.md`,
    date: '2023-12-06', standing: 'CURRENT',
    title: 'VER-0012 — legacy finality verification',
    body: [
      '# VER-0012 — legacy finality verification',
      '',
      '**Date:** 2023-12-06  **Subject:** REV-0004  **Result:** PASS',
      '',
      '## Cases',
      '',
      '1. tenant with legacy DENY and a newer ALLOW from the same tenant — resolver returns DENY. PASS',
      '2. tenant with legacy DENY and a newer ALLOW inherited from a parent group — resolver returns DENY. PASS',
      '3. tenant with only an ALLOW — resolver returns ALLOW. PASS',
      '4. tenant with only a legacy DENY — resolver returns DENY. PASS',
      '',
      '## Note',
      '',
      'Case 2 is the one that matters: it is the shape INC-0007 actually had. Every case here uses a tenant whose',
      'decisions all predate the cutover, because at this date no tenant had a cutover date yet.',
      '',
    ].join(NL),
  }),

  Object.freeze({
    id: 'DEC-0044', category: 'DECISION', path: `${CORPUS_ROOT}/decisions/0044-post-cutover-tenants-exempt.md`,
    date: '2024-02-08', standing: 'SUPERSEDED_IN_PART',
    title: 'DEC-0044 — post-cutover tenants are exempt from legacy finality',
    body: [
      '# DEC-0044 — post-cutover tenants are exempt from legacy finality',
      '',
      '**Date:** 2024-02-08  **Status:** accepted  **Supersedes in part:** DEC-0031  **Superseded in part by:** REV-0009',
      '',
      '## Decision',
      '',
      'Legacy finality applies to tenants that existed under the legacy engine. For a tenant onboarded AFTER the',
      'cutover, the new engine is authoritative and an inherited ALLOW may overturn an inherited DENY.',
      '',
      '## Why the rule had to change',
      '',
      'INC-0007 was about a tenant the legacy engine had genuinely evaluated. A tenant onboarded after the cutover',
      'has no legacy decision of its own; an inherited DENY that arrives from a parent group was never a decision',
      'about that tenant at all. Applying legacy finality to it protected a fact that did not exist.',
      '',
      '## How a tenant is classified',
      '',
      'By ONBOARDING DATE: a tenant onboarded before the cutover is legacy; a tenant onboarded on or after it is',
      'post-cutover.',
      '',
      '## Note for readers',
      '',
      'The classification rule above was revised three weeks later. Onboarding date turned out not to be the',
      'right key — see REV-0009, which is the rule that currently stands.',
      '',
    ].join(NL),
  }),

  Object.freeze({
    id: 'REV-0009', category: 'REVISION', path: `${CORPUS_ROOT}/revisions/0009-cutover-date-is-the-key.md`,
    date: '2024-03-01', standing: 'CURRENT',
    title: 'REV-0009 — the tenant cutover date is the key, not the onboarding date',
    body: [
      '# REV-0009 — the tenant cutover date is the key, not the onboarding date',
      '',
      '**Date:** 2024-03-01  **Supersedes:** DEC-0044 (classification rule only)  **Status:** CURRENT',
      '',
      '## Change',
      '',
      'The classification is made by the tenant\'s own `cutoverDate`, and the rule is about the DECISION\'s date:',
      '',
      '- a legacy DENY recorded BEFORE the tenant\'s cutover date is FINAL and no later ALLOW overturns it;',
      '- from the tenant\'s cutover date onward, the new engine is authoritative and ordinary latest-wins applies;',
      '- an ALLOW recorded before the cutover is NOT protected the way a DENY is — only DENYs are final.',
      '',
      '## Why onboarding date was wrong',
      '',
      'INC-0019. A tenant onboarded in 2022 was MIGRATED onto the new engine in 2024. Its onboarding date said',
      '"legacy", so legacy finality applied to decisions recorded after its migration — decisions the new engine',
      'had made, and which the rule was never meant to cover. A tenant\'s onboarding date and its migration date',
      'differ, and the migration date is the one that changes which engine is authoritative.',
      '',
      '## Consequences',
      '',
      '- `cutoverDate` is stored per tenant and is the ONLY key;',
      '- the comparison is between the DECISION\'s `recordedAt` and the tenant\'s `cutoverDate`;',
      '- two tenants with identical decision histories can therefore resolve DIFFERENTLY, and that is correct;',
      '- a tenant with no `cutoverDate` has never been migrated, so every one of its decisions is legacy.',
      '',
      '## Verification',
      '',
      'VER-0031 covers this revision. It is the verification that currently stands.',
      '',
    ].join(NL),
  }),

  Object.freeze({
    id: 'INC-0019', category: 'INCIDENT', path: `${CORPUS_ROOT}/incidents/0019-onboarding-date-misclassification.md`,
    date: '2024-02-27', standing: 'CURRENT',
    title: 'INC-0019 — onboarding date misclassified a migrated tenant',
    body: [
      '# INC-0019 — onboarding date misclassified a migrated tenant',
      '',
      '**Date:** 2024-02-27  **Severity:** medium  **Status:** resolved by REV-0009',
      '',
      '## What happened',
      '',
      'Tenant `contoso` onboarded in 2022 and was migrated onto the new engine on 2024-01-10. Its onboarding date',
      'classified it as legacy, so legacy finality was applied to a DENY the NEW engine recorded on 2024-02-01.',
      'The tenant was refused a capability the new engine had explicitly granted, and the refusal survived an',
      'operator\'s correction for two days.',
      '',
      '## Root cause',
      '',
      'DEC-0044 keyed the classification on onboarding date. Onboarding date and migration date are different',
      'facts, and only the migration date changes which engine is authoritative for a given decision.',
      '',
      '## Resolution',
      '',
      'REV-0009 replaced the key with the tenant\'s `cutoverDate`. The comparison is now between the decision\'s own',
      'date and that cutover date, so a migrated tenant\'s post-migration decisions are evaluated by the new engine.',
      '',
    ].join(NL),
  }),

  Object.freeze({
    id: 'VER-0031', category: 'VERIFICATION', path: `${CORPUS_ROOT}/verification/0031-cutover-precedence.md`,
    date: '2024-03-04', standing: 'CURRENT',
    title: 'VER-0031 — cutover precedence verification',
    body: [
      '# VER-0031 — cutover precedence verification',
      '',
      '**Date:** 2024-03-04  **Subject:** REV-0009  **Result:** PASS',
      '',
      '## Cases',
      '',
      '1. DENY recorded before the tenant cutover, ALLOW recorded after it — resolver returns DENY. PASS',
      '2. DENY recorded after the tenant cutover, ALLOW recorded later still — resolver returns ALLOW. PASS',
      '3. ALLOW recorded before the tenant cutover, DENY recorded after it — resolver returns DENY. PASS',
      '   (an ALLOW before the cutover is not protected; only DENYs are)',
      '4. the SAME decision history under two tenants with different cutover dates — the two tenants resolve',
      '   differently. PASS. This is the case that proves the cutover date is the key.',
      '5. a tenant with no cutover date — every decision is treated as legacy. PASS',
      '',
      '## Coverage note',
      '',
      'These cases cover the precedence rule. They do NOT cover the capability consolidation, which is a separate',
      'change tracked under DEC-0058.',
      '',
    ].join(NL),
  }),

  Object.freeze({
    id: 'MIG-0006', category: 'MIGRATION', path: `${CORPUS_ROOT}/migration/0006-legacy-tenant-migration-notes.md`,
    date: '2024-03-11', standing: 'CURRENT',
    title: 'MIG-0006 — migrating a legacy tenant onto the new engine',
    body: [
      '# MIG-0006 — migrating a legacy tenant onto the new engine',
      '',
      '**Date:** 2024-03-11  **Applies to:** tenants onboarded before the cutover',
      '',
      '## Procedure',
      '',
      '1. record the migration date as the tenant\'s `cutoverDate` — this is the only field the precedence rule reads;',
      '2. leave every existing decision untouched, INCLUDING its `source` and `recordedAt`;',
      '3. do NOT rewrite a legacy decision\'s source to `new`, even though the tenant now runs on the new engine —',
      '   the source records which engine MADE the decision, not which engine the tenant currently uses;',
      '4. re-run the resolver\'s verification for the tenant.',
      '',
      '## What changes after migration',
      '',
      'Decisions recorded BEFORE the cutover keep their legacy status, so a legacy DENY among them remains final.',
      'Decisions recorded AFTER the cutover are the new engine\'s and follow ordinary latest-wins.',
      '',
      '## Common mistake',
      '',
      'Setting `cutoverDate` to the ONBOARDING date. That is the mistake INC-0019 records. The cutover date is the',
      'date the tenant STARTED being evaluated by the new engine, which for a migrated tenant is the migration',
      'date and not the date the tenant first appeared.',
      '',
    ].join(NL),
  }),

  /* ============================================================ the I2 lineage */

  Object.freeze({
    id: 'DEC-0058', category: 'DECISION', path: `${CORPUS_ROOT}/decisions/0058-consolidate-ledger-capabilities.md`,
    date: '2024-04-02', standing: 'CURRENT',
    title: 'DEC-0058 — consolidate three ledger capabilities into one',
    body: [
      '# DEC-0058 — consolidate three ledger capabilities into one',
      '',
      '**Date:** 2024-04-02  **Status:** accepted  **Supersedes in part:** the independence of the three named capabilities',
      '',
      '## Decision',
      '',
      'Three legacy ledger capabilities are consolidated into a single capability:',
      '',
      '| legacy name | becomes an alias of |',
      '| --- | --- |',
      '| `ledger.view` | `ledger.operate` |',
      '| `ledger.edit` | `ledger.operate` |',
      '| `ledger.approve` | `ledger.operate` |',
      '',
      'Every OTHER legacy capability keeps its own independent grant set. `ledger.export` in particular is NOT',
      'part of this consolidation and is unaffected by it.',
      '',
      '## Why',
      '',
      'The new engine evaluates `ledger.operate` as one authority. Operators were granting the three legacy names',
      'separately and getting three different answers about the same underlying authority.',
      '',
      '## Consequences',
      '',
      '- the three legacy names are preserved as ALIASES, so historical records stay readable;',
      '- a tenant holding any of the three legacy names holds `ledger.operate`;',
      '- the aliases are not deleted, and must not be deleted, because the audit trail names them.',
      '',
      '## Open question, recorded at the time',
      '',
      'What happens when a tenant holds BOTH an alias and `ledger.operate` directly, and one of them is revoked.',
      'This decision did not settle it. See INC-0071.',
      '',
    ].join(NL),
  }),

  Object.freeze({
    id: 'INC-0071', category: 'INCIDENT', path: `${CORPUS_ROOT}/incidents/0071-alias-revocation-left-access.md`,
    date: '2024-04-18', standing: 'CURRENT',
    title: 'INC-0071 — revoking an alias left the consolidated access in place',
    body: [
      '# INC-0071 — revoking an alias left the consolidated access in place',
      '',
      '**Date:** 2024-04-18  **Severity:** high  **Status:** resolved by REV-0017',
      '',
      '## What happened',
      '',
      'An operator revoked `ledger.approve` from tenant `adventure-works` after an offboarding request. The tenant',
      'had been granted `ledger.approve` before the consolidation and `ledger.operate` after it. The revocation',
      'removed the `ledger.approve` record, and the tenant KEPT access, because the `ledger.operate` record was',
      'still there and the resolver found it.',
      '',
      'The operator believed access was removed. It was not, and the tenant approved a further payment run.',
      '',
      '## Root cause',
      '',
      'The revocation removed the record it was NAMED for and nothing else. It had no notion that two records',
      'could carry the same authority after DEC-0058. The consolidation made two records equivalent for GRANTING',
      'but the revocation path still treated them as independent.',
      '',
      '## Resolution',
      '',
      'REV-0017. A revocation now removes the tenant\'s ACCESS to the consolidated capability when the tenant holds',
      'the revoked name. The exact rule, including the case where the tenant does not hold the named record, is in',
      'REV-0017 and is verified by VER-0052.',
      '',
    ].join(NL),
  }),

  Object.freeze({
    id: 'REV-0017', category: 'REVISION', path: `${CORPUS_ROOT}/revisions/0017-consolidated-grant-is-authoritative.md`,
    date: '2024-04-25', standing: 'CURRENT',
    title: 'REV-0017 — the consolidated grant is authoritative for access',
    body: [
      '# REV-0017 — the consolidated grant is authoritative for access',
      '',
      '**Date:** 2024-04-25  **Supersedes:** the assumption that alias and consolidated records are independent',
      '**Status:** CURRENT',
      '',
      '## Change',
      '',
      'For a capability named in DEC-0058:',
      '',
      '- the consolidated name (`ledger.operate`) is AUTHORITATIVE for whether the tenant has access;',
      '- a legacy alias and the consolidated name are the SAME authority, so holding both is holding one;',
      '- **a revocation acts only if the tenant HOLDS the revoked name**; when it does, the revocation removes',
      '  the tenant\'s access to the capability by removing EVERY record of the tenant\'s that maps to it, not',
      '  merely the named one;',
      '- when the tenant does NOT hold the revoked name, the revocation removes NOTHING — an alias the tenant',
      '  does not hold is not a wildcard over the capability;',
      '- the alias record is PRESERVED for provenance and does not count as a second grant.',
      '',
      '## Why the rule is stated in both directions',
      '',
      'The first direction fixes INC-0071: revoking `ledger.view` from a tenant that holds `ledger.view` AND',
      '`ledger.operate` must remove access, and the naive implementation removed only `ledger.view`.',
      '',
      'The second direction is the one that is easy to get wrong while fixing the first. An implementation that',
      'maps the revoked name to `ledger.operate` and revokes that instead would remove access from a tenant that',
      'never held the revoked name — a revocation the operator did not ask for, against a tenant it did not name.',
      'Access is decided by what the tenant HOLDS, and the revoked name must be among it.',
      '',
      '## Why "authoritative" rather than "either"',
      '',
      'The alternative was to treat either record as sufficient. That is what caused INC-0071: a revocation of one',
      'left the other, and access survived. Making the capability — not the record — the unit of access means a',
      'revocation removes every record of the tenant that maps to it, so nothing is left behind.',
      '',
      '## Preserved, not counted twice',
      '',
      'The alias record is PRESERVED for provenance — the audit trail names it — but it does not count as a second',
      'grant. A tenant holding both does not hold two.',
      '',
      '## Scope',
      '',
      'Only the three capabilities DEC-0058 names. A capability outside that list keeps its independent grant set,',
      'and revoking it affects only itself.',
      '',
      '## Verification',
      '',
      'VER-0052 covers this revision.',
      '',
    ].join(NL),
  }),

  Object.freeze({
    id: 'VER-0052', category: 'VERIFICATION', path: `${CORPUS_ROOT}/verification/0052-alias-revocation.md`,
    date: '2024-04-29', standing: 'CURRENT',
    title: 'VER-0052 — alias revocation verification',
    body: [
      '# VER-0052 — alias revocation verification',
      '',
      '**Date:** 2024-04-29  **Subject:** REV-0017  **Result:** PASS',
      '',
      '## Cases',
      '',
      '1. tenant holds `ledger.view` only; revoke `ledger.view`; tenant has no `ledger.operate`. PASS',
      '2. tenant holds `ledger.operate` only; revoke `ledger.view`; tenant STILL has `ledger.operate`. PASS',
      '   (an alias the tenant does not hold is not a wildcard)',
      '3. tenant holds `ledger.view` AND `ledger.operate`; revoke `ledger.view`; tenant has no `ledger.operate`.',
      '   PASS. This is the INC-0071 shape and is the case the revision exists for.',
      '4. tenant holds `ledger.edit`; revoke `ledger.approve`; tenant STILL has `ledger.operate`. PASS',
      '   (revoking an alias the tenant does not hold removes nothing)',
      '5. tenant holds `ledger.export`; revoke `ledger.view`; tenant STILL has `ledger.export`. PASS',
      '   (`ledger.export` is outside the consolidation)',
      '6. tenant holds `ledger.view`; revoke `ledger.export`; tenant STILL has `ledger.operate`. PASS',
      '',
      '## Note',
      '',
      'Cases 2 and 4 are the pair that distinguishes "the alias is a name for the capability" from "the alias is a',
      'wildcard that removes whatever it is asked to". Case 5 is the applicability boundary.',
      '',
    ].join(NL),
  }),

  Object.freeze({
    id: 'MIG-0011', category: 'MIGRATION', path: `${CORPUS_ROOT}/migration/0011-alias-holder-migration.md`,
    date: '2024-05-06', standing: 'CURRENT',
    title: 'MIG-0011 — what alias holders should expect after consolidation',
    body: [
      '# MIG-0011 — what alias holders should expect after consolidation',
      '',
      '**Date:** 2024-05-06  **Applies to:** tenants holding any of the three consolidated legacy names',
      '',
      '## For an operator',
      '',
      '- a tenant holding `ledger.view`, `ledger.edit` or `ledger.approve` has `ledger.operate`;',
      '- revoking any of those three names removes `ledger.operate`, even if the tenant also holds it directly;',
      '- revoking a name the tenant does NOT hold removes nothing, even if it is one of the three;',
      '- capabilities outside the three are unaffected — check DEC-0058 for the exact list before assuming.',
      '',
      '## For a developer',
      '',
      'Do not write code that maps an alias to the consolidated name and then revokes the mapped name. That',
      'reintroduces INC-0071 in a different place: the tenant may hold the consolidated name directly, and the',
      'mapped revocation would miss it. Decide access by the CAPABILITY.',
      '',
      '## Historical note',
      '',
      'Before DEC-0058 the three names were independent and revoking one affected only itself. Code written then',
      'is not wrong for a capability outside the consolidation, and is wrong for the three inside it.',
      '',
    ].join(NL),
  }),

  /* ============================================================ superseded rules, clearly marked */

  Object.freeze({
    id: 'DEC-0012', category: 'DECISION', path: `${CORPUS_ROOT}/decisions/0012-capabilities-are-independent.md`,
    date: '2021-06-30', standing: 'SUPERSEDED',
    title: 'DEC-0012 — every capability has an independent grant set',
    body: [
      '# DEC-0012 — every capability has an independent grant set',
      '',
      '**Date:** 2021-06-30  **Status:** SUPERSEDED by DEC-0058 for the three consolidated capabilities',
      '',
      '## Decision',
      '',
      'Each capability is granted and revoked independently. A grant of one capability never affects another, and a',
      'revocation of one removes only that one.',
      '',
      '## Status note',
      '',
      'This decision is SUPERSEDED for `ledger.view`, `ledger.edit` and `ledger.approve`, which DEC-0058',
      'consolidated into `ledger.operate`. It REMAINS IN FORCE for every other capability, including',
      '`ledger.export`.',
      '',
      'A reader who applies this decision to the three consolidated names will reproduce INC-0071.',
      '',
    ].join(NL),
  }),

  Object.freeze({
    id: 'DOC-0003', category: 'CURRENT_AND_SUPERSEDED', path: `${CORPUS_ROOT}/guides/0003-entitlement-resolution-guide.md`,
    date: '2023-08-02', standing: 'SUPERSEDED_IN_PART',
    title: 'Guide — resolving a tenant entitlement',
    body: [
      '# Guide — resolving a tenant entitlement',
      '',
      '**Date:** 2023-08-02  **Last reviewed:** 2023-08-02  **Status:** partially superseded',
      '',
      '> This guide was written before the cutover work. The precedence section below describes the rule as it',
      '> stood in 2023. Read DEC-0044, REV-0009 and REV-0017 for the rules that currently stand; this document is',
      '> kept because its data-model description is still accurate.',
      '',
      '## The data model (still accurate)',
      '',
      'A tenant has a `cutoverDate`, which is the date it began being evaluated by the new engine. A decision has a',
      '`source` (`legacy` or `new`), a `recordedAt` date, an `effect` (`ALLOW` or `DENY`) and a `capability`.',
      '',
      'The `source` records which engine MADE the decision. It is never rewritten, even when the tenant migrates.',
      '',
      '## Precedence (SUPERSEDED — do not implement from this section)',
      '',
      'In 2023 the rule was: the most recently recorded decision wins. This was replaced after INC-0007, because a',
      'legacy DENY was being overturned by a newer inherited ALLOW.',
      '',
      '## Effective date (still accurate)',
      '',
      'A resolution is made AS OF a date. A decision recorded after that date does not exist for that resolution.',
      '',
    ].join(NL),
  }),

  /* ============================================================ ordinary, irrelevant-but-plausible history */

  Object.freeze({
    id: 'DEC-0021', category: 'IRRELEVANT_PLAUSIBLE', path: `${CORPUS_ROOT}/decisions/0021-structured-logging.md`,
    date: '2022-09-14', standing: 'CURRENT',
    title: 'DEC-0021 — adopt structured logging in the entitlement service',
    body: [
      '# DEC-0021 — adopt structured logging in the entitlement service',
      '',
      '**Date:** 2022-09-14  **Status:** accepted',
      '',
      '## Decision',
      '',
      'The service emits one JSON object per request, including the tenant id, the capability, the resolver',
      'outcome and the resolver version. Free-text log lines are retired.',
      '',
      '## Why',
      '',
      'INC-0011 took four hours to diagnose because the relevant log line was a sentence. Structured fields make',
      'the same question a query.',
      '',
      '## Consequences',
      '',
      '- every resolver outcome is logged with the tenant and capability;',
      '- log volume roughly doubled, which was accepted;',
      '- no decision data is logged, only identifiers and outcomes.',
      '',
    ].join(NL),
  }),

  Object.freeze({
    id: 'REV-0022', category: 'IRRELEVANT_PLAUSIBLE', path: `${CORPUS_ROOT}/revisions/0022-log-sampling.md`,
    date: '2023-02-03', standing: 'SUPERSEDED',
    title: 'REV-0022 — sample resolver logs above 1000 requests per minute',
    body: [
      '# REV-0022 — sample resolver logs above 1000 requests per minute',
      '',
      '**Date:** 2023-02-03  **Status:** SUPERSEDED by REV-0038',
      '',
      '## Change',
      '',
      'Above 1000 resolver requests per minute, sample the log stream at 10%.',
      '',
      '## Superseded',
      '',
      'This was reverted by REV-0038 after an audit found the sampled window contained no record of a decision that',
      'was later disputed. Logging cost was addressed by compression instead.',
      '',
    ].join(NL),
  }),

  Object.freeze({
    id: 'REV-0038', category: 'IRRELEVANT_PLAUSIBLE', path: `${CORPUS_ROOT}/revisions/0038-log-compression.md`,
    date: '2023-05-19', standing: 'CURRENT',
    title: 'REV-0038 — compress resolver logs instead of sampling them',
    body: [
      '# REV-0038 — compress resolver logs instead of sampling them',
      '',
      '**Date:** 2023-05-19  **Supersedes:** REV-0022  **Status:** CURRENT',
      '',
      '## Change',
      '',
      'Resolver logs are no longer sampled. The stream is compressed at rest, which reduced storage by more than',
      'the sampling had, without dropping records.',
      '',
      '## Verification',
      '',
      'VER-0029 measured a 71% storage reduction against the sampled baseline and found no missing decisions in a',
      'one-week window.',
      '',
    ].join(NL),
  }),

  Object.freeze({
    id: 'INC-0033', category: 'IRRELEVANT_PLAUSIBLE', path: `${CORPUS_ROOT}/incidents/0033-timezone-in-daily-report.md`,
    date: '2023-09-27', standing: 'CURRENT',
    title: 'INC-0033 — the daily entitlement report used the wrong timezone',
    body: [
      '# INC-0033 — the daily entitlement report used the wrong timezone',
      '',
      '**Date:** 2023-09-27  **Severity:** low  **Status:** resolved',
      '',
      '## What happened',
      '',
      'The daily report grouped decisions by local date while the service recorded UTC. Decisions between midnight',
      'and 01:00 local appeared in the previous day\'s report.',
      '',
      '## Resolution',
      '',
      'The report now groups by UTC and prints the timezone in its header. This affected REPORTING only — the',
      'stored `recordedAt` values were always UTC and were never wrong.',
      '',
      '## Note',
      '',
      'Worth recording because it is a date bug in the same service. It did not affect resolution: the resolver has',
      'always compared dates as stored.',
      '',
    ].join(NL),
  }),

  Object.freeze({
    id: 'DEC-0047', category: 'IRRELEVANT_PLAUSIBLE', path: `${CORPUS_ROOT}/decisions/0047-rate-limit-per-tenant.md`,
    date: '2024-01-19', standing: 'CURRENT',
    title: 'DEC-0047 — rate limit resolution per tenant',
    body: [
      '# DEC-0047 — rate limit resolution per tenant',
      '',
      '**Date:** 2024-01-19  **Status:** accepted',
      '',
      '## Decision',
      '',
      'Resolution requests are rate limited per tenant at 600 per minute, with a burst allowance of 120.',
      '',
      '## Why',
      '',
      'A single misconfigured client was issuing 40k requests per minute and degrading resolution for everyone.',
      '',
      '## Consequences',
      '',
      '- the limit is per tenant, so one tenant cannot exhaust another\'s budget;',
      '- exceeded requests receive 429 with a retry-after header;',
      '- the resolver itself is unchanged; this is a front-door concern.',
      '',
    ].join(NL),
  }),

  Object.freeze({
    id: 'INC-0055', category: 'IRRELEVANT_PLAUSIBLE', path: `${CORPUS_ROOT}/incidents/0055-dashboard-stale-cache.md`,
    date: '2024-03-22', standing: 'CURRENT',
    title: 'INC-0055 — the operator dashboard served a stale entitlement cache',
    body: [
      '# INC-0055 — the operator dashboard served a stale entitlement cache',
      '',
      '**Date:** 2024-03-22  **Severity:** medium  **Status:** resolved',
      '',
      '## What happened',
      '',
      'The operator dashboard cached resolved entitlements for 15 minutes. After a revocation, the dashboard kept',
      'showing the tenant as allowed, and an operator concluded the revocation had failed.',
      '',
      '## Resolution',
      '',
      'The dashboard cache was reduced to 30 seconds and a manual refresh was added. The RESOLVER was correct',
      'throughout; the stale view was the dashboard\'s.',
      '',
      '## Note',
      '',
      'Recorded because it is superficially similar to INC-0071 — an operator believed access was removed and it',
      'was not. The cause here was a cache, not a precedence rule, and the fix was entirely in the dashboard.',
      '',
    ].join(NL),
  }),

  Object.freeze({
    id: 'VER-0060', category: 'IRRELEVANT_PLAUSIBLE', path: `${CORPUS_ROOT}/verification/0060-load-profile.md`,
    date: '2024-05-30', standing: 'CURRENT',
    title: 'VER-0060 — resolver load profile',
    body: [
      '# VER-0060 — resolver load profile',
      '',
      '**Date:** 2024-05-30  **Subject:** capacity  **Result:** PASS',
      '',
      '## Findings',
      '',
      'The resolver sustains 4200 resolutions per second on the reference host with p99 latency of 8ms. The',
      'precedence rule added by REV-0009 costs one date comparison per stored decision, which was not measurable',
      'against the profile noise.',
      '',
      '## Note',
      '',
      'Capacity only. This document says nothing about correctness and should not be cited as evidence that any',
      'precedence rule is right.',
      '',
    ].join(NL),
  }),

  Object.freeze({
    id: 'DOC-0008', category: 'IRRELEVANT_PLAUSIBLE', path: `${CORPUS_ROOT}/guides/0008-onboarding-checklist.md`,
    date: '2024-06-04', standing: 'CURRENT',
    title: 'Guide — onboarding a new tenant',
    body: [
      '# Guide — onboarding a new tenant',
      '',
      '**Date:** 2024-06-04  **Audience:** operators',
      '',
      '## Checklist',
      '',
      '1. create the tenant record with its `onboardedAt` date;',
      '2. if the tenant is being migrated from the legacy engine, ALSO record its `cutoverDate`;',
      '3. grant the initial capabilities;',
      '4. confirm the resolver returns the expected outcome;',
      '5. record the onboarding in the tenant register.',
      '',
      '## Note on step 2',
      '',
      'A tenant that has never run on the legacy engine has no `cutoverDate` and needs none. A tenant that HAS is',
      'not fully onboarded until the cutover date is recorded — the precedence rule reads that field and nothing',
      'else. See MIG-0006.',
      '',
    ].join(NL),
  }),

  Object.freeze({
    id: 'REV-0063', category: 'IRRELEVANT_PLAUSIBLE', path: `${CORPUS_ROOT}/revisions/0063-rename-internal-module.md`,
    date: '2024-07-15', standing: 'CURRENT',
    title: 'REV-0063 — rename the internal resolver module',
    body: [
      '# REV-0063 — rename the internal resolver module',
      '',
      '**Date:** 2024-07-15  **Status:** CURRENT',
      '',
      '## Change',
      '',
      'The internal module `policy/resolve.js` was renamed to `policy/decide.js`. No behaviour changed.',
      '',
      '## Why',
      '',
      'The old name collided with the public `resolve` verb and made stack traces ambiguous.',
      '',
      '## Consequences',
      '',
      'None functionally. Import paths in the service changed; nothing stored changed.',
      '',
    ].join(NL),
  }),

  Object.freeze({
    id: 'INC-0066', category: 'IRRELEVANT_PLAUSIBLE', path: `${CORPUS_ROOT}/incidents/0066-audit-export-truncated.md`,
    date: '2024-08-01', standing: 'CURRENT',
    title: 'INC-0066 — the audit export truncated at 10,000 rows',
    body: [
      '# INC-0066 — the audit export truncated at 10,000 rows',
      '',
      '**Date:** 2024-08-01  **Severity:** low  **Status:** resolved',
      '',
      '## What happened',
      '',
      'A compliance export silently stopped at 10,000 rows. The export had no pagination and no truncation notice.',
      '',
      '## Resolution',
      '',
      'The export now paginates and states the total row count in its footer. No decision data was ever lost; only',
      'the export was incomplete.',
      '',
    ].join(NL),
  }),
]);

/** §5: every document of a category. */
export function documentsOf(category) {
  return Object.freeze(CORPUS_DOCUMENTS.filter((entry) => entry.category === category));
}

/** §5: the corpus file map, as the Project world writes it. */
export function corpusFiles() {
  const files = {};
  for (const document of CORPUS_DOCUMENTS) files[document.path] = document.body;
  return Object.freeze(files);
}

/** §5: the frozen corpus digest material, so the bytes cannot change after the plan is frozen. */
export function corpusDigestMaterial() {
  return CORPUS_DOCUMENTS.map((document) => `${document.id}:${document.path}:${document.body}`).join(NL + NL);
}

/**
 * §5: THE CATEGORY COVERAGE, asserted so a missing category is a failure rather than a surprise.
 *
 * §5 requires each listed category to be PRESENT, so this returns what is present and what is missing, and the
 * plan records it. A corpus missing a category would make the reconstruction easier than §5 intends.
 */
export function corpusCoverage() {
  const present = {};
  for (const document of CORPUS_DOCUMENTS) present[document.category] = (present[document.category] ?? 0) + 1;
  const missing = CORPUS_CATEGORIES.filter((entry) => entry.required && (present[entry.id] ?? 0) === 0).map((entry) => entry.id);
  return Object.freeze({
    documents: CORPUS_DOCUMENTS.length,
    byCategory: Object.freeze(present),
    missingRequiredCategories: Object.freeze(missing),
    complete: missing.length === 0,
    bytes: Object.freeze(Object.fromEntries(CORPUS_DOCUMENTS.map((document) => [document.id, document.body.length]))),
    totalBytes: CORPUS_DOCUMENTS.reduce((total, document) => total + document.body.length, 0),
  });
}

/**
 * §5/§6: THE DECLARED RAW-HISTORY CORPUS, as the set the reconstruction-cost outcome counts.
 *
 * Only these paths count as raw-history reads. The distinction is what keeps a capital body from being counted
 * as a history byte, which §13 requires.
 */
export function declaredCorpusPaths() {
  return Object.freeze(CORPUS_DOCUMENTS.map((document) => document.path));
}

/** §5: whether a path is a declared corpus document. */
export function isDeclaredCorpusPath(path) {
  const normalized = String(path).replace(/\\/gu, '/');
  return CORPUS_DOCUMENTS.some((document) => normalized.endsWith(document.path) || normalized.endsWith(document.path.split('/').pop() ?? ''));
}
