/**
 * SR-1 §7/§8/§40 — render the architecture model into the required artifacts.
 *
 * Everything here is derived from `analyseModuleArchitecture()`; the documents are views
 * of the measured graph, never a hand-maintained parallel description of it.
 */

import type { ArchitectureCheckResult, ArchitectureBaseline } from "./rules.js";
import type { ModuleArchitecture, ModuleNode } from "./graph.js";
import { LOGICAL_LAYERS, type LogicalLayer } from "./layers.js";

const asKb = (bytes: number): string => `${(bytes / 1024).toFixed(1)} KB`;

const table = (header: readonly string[], rows: readonly (readonly string[])[]): string =>
  [`| ${header.join(" | ")} |`, `| ${header.map(() => "---").join(" | ")} |`, ...rows.map((row) => `| ${row.join(" | ")} |`)].join("\n");

export function renderBaselineDocument(
  architecture: ModuleArchitecture,
  baseline: ArchitectureBaseline,
  options: { readonly generatedAt: string; readonly stage: string },
): string {
  const top = <T>(items: readonly T[], key: (item: T) => number, take: number): readonly T[] =>
    [...items].sort((a, b) => key(b) - key(a)).slice(0, take);

  const topFanOut = top(architecture.modules, (node) => node.fanOut, 15);
  const topFanIn = top(architecture.modules, (node) => node.fanIn, 15);
  const biggest = top(architecture.modules, (node) => node.loc, 15);
  const layerCounts = LOGICAL_LAYERS.map((layer) => {
    const modules = architecture.modules.filter((node) => node.layer === layer);
    return {
      layer,
      files: modules.length,
      loc: modules.reduce((sum, node) => sum + node.loc, 0),
      bytes: modules.reduce((sum, node) => sum + node.bytes, 0),
    };
  });

  const hotspots = ["src/install.ts", "src/tools/controller.ts", "src/application/surface.ts", "src/tools/application_tools.ts", "src/application/http.ts", "src/deployment/launch.ts", "src/index.ts", "src/advanced.ts"]
    .map((file) => architecture.modules.find((node) => node.file === file))
    .filter((node): node is ModuleNode => node !== undefined);

  return `# Module architecture baseline (SR-1 R0)

Generated by \`tools/architecture\` (\`node scripts/audit/module-architecture.mjs --write\`) at
${options.generatedAt} from stage \`${options.stage}\`.

This document is a **view of the measured graph**, not a hand-maintained description. Every
number below comes from parsing the real sources with the TypeScript compiler API.

## 1. Totals

${table(
  ["metric", "value"],
  [
    ["modules under `src/**`", String(architecture.totals.files)],
    ["lines of TypeScript", String(architecture.totals.loc)],
    ["source bytes", asKb(architecture.totals.bytes)],
    ["intra-repository import edges", String(architecture.totals.edges)],
    ["distinct external packages", String(architecture.totals.externalImports)],
    ["unresolved relative imports", String(architecture.totals.unresolvedImports)],
    ["forbidden layer edges (recorded as exceptions)", String(architecture.forbiddenEdges.length)],
    ["strongly connected components", String(architecture.stronglyConnectedComponents.length)],
  ],
)}

## 2. Modules per logical layer (§6)

${table(
  ["layer", "modules", "LOC", "bytes"],
  layerCounts.map((entry) => [entry.layer, String(entry.files), String(entry.loc), asKb(entry.bytes)]),
)}

## 3. The named hotspots (§4/§8)

${table(
  ["module", "layer", "LOC", "bytes", "direct imports (fan-out)", "direct importers (fan-in)"],
  hotspots.map((node) => [node.file, node.layer, String(node.loc), asKb(node.bytes), String(node.fanOut), String(node.fanIn)]),
)}

## 4. Top fan-out (composition knowledge concentration)

${table(
  ["module", "layer", "fan-out", "fan-in", "LOC"],
  topFanOut.map((node) => [node.file, node.layer, String(node.fanOut), String(node.fanIn), String(node.loc)]),
)}

## 5. Top fan-in (change-radius multipliers)

${table(
  ["module", "layer", "fan-in", "fan-out", "LOC"],
  topFanIn.map((node) => [node.file, node.layer, String(node.fanIn), String(node.fanOut), String(node.loc)]),
)}

## 6. Largest modules

${table(
  ["module", "layer", "LOC", "bytes", "fan-out", "fan-in"],
  biggest.map((node) => [node.file, node.layer, String(node.loc), asKb(node.bytes), String(node.fanOut), String(node.fanIn)]),
)}

## 7. Layer dependency matrix (observed edges)

${table(
  ["from → to", "imports", "allowed?"],
  architecture.layerEdges.map((edge) => [
    `${edge.fromLayer} → ${edge.toLayer}`,
    String(edge.count),
    architectureForbidden(architecture, edge.fromLayer, edge.toLayer) ? "**no (baseline exception)**" : "yes",
  ]),
)}

## 8. Forbidden layer edges (the recorded baseline exceptions)

${table(
  ["edge", "imports", "reason"],
  architecture.forbiddenEdges.map((edge) => {
    const key = `${edge.fromLayer}->${edge.toLayer}`;
    const recorded = baseline.permittedForbiddenLayerEdges.find((entry) => entry.edge === key);
    return [`${edge.fromLayer} → ${edge.toLayer}`, String(edge.count), recorded?.reason ?? "_not recorded_"];
  }),
)}

A forbidden edge that is not in the table above **fails** \`pnpm architecture:check\`.

## 9. Directory dependency matrix (top 40 by volume)

${table(
  ["from → to", "imports"],
  architecture.directoryEdges.slice(0, 40).map((edge) => [edge.from + " → " + edge.to, String(edge.count)]),
)}

## 10. Strongly connected components

${table(
  ["size", "layers", "members"],
  architecture.stronglyConnectedComponents.map((cycle) => {
    const layers = [...new Set(cycle.files.map((file) => architecture.modules.find((node) => node.file === file)?.layer ?? "?"))].sort();
    return [String(cycle.size), layers.join("/"), cycle.files.slice(0, 6).join("<br>") + (cycle.size > 6 ? `<br>… ${cycle.size - 6} more` : "")];
  }),
)}

## 11. Public export surface (barrels)

${table(
  ["barrel", "exported names (~)"],
  architecture.exportSurface.map((entry) => [entry.file, String(entry.exports.length)]),
)}

## 12. How to reproduce

\`\`\`text
pnpm architecture:write    # regenerate architecture/module-architecture.json + this document
pnpm architecture:check    # fail on a NEW forbidden edge, a NEW cross-layer cycle, an unresolved import
\`\`\`
`;
}

function architectureForbidden(architecture: ModuleArchitecture, from: LogicalLayer, to: LogicalLayer): boolean {
  return architecture.forbiddenEdges.some((edge) => edge.fromLayer === from && edge.toLayer === to);
}

export function renderCheckSummary(result: ArchitectureCheckResult): string {
  const lines = [
    `architecture:check ${result.ok ? "PASS" : "FAIL"}`,
    `  violations: ${result.violations.length}`,
    `  accepted baseline exceptions observed: ${result.accepted.length}`,
  ];
  for (const violation of result.violations) lines.push(`  [${violation.kind}] ${violation.detail}`);
  return lines.join("\n");
}

/** The machine-readable baseline (§7): metrics + the explicit exceptions. */
export function toJson(architecture: ModuleArchitecture, baseline: ArchitectureBaseline): string {
  const payload = {
    version: baseline.version,
    capturedFrom: baseline.capturedFrom,
    totals: architecture.totals,
    layers: LOGICAL_LAYERS.map((layer) => ({
      layer,
      files: architecture.modules.filter((node) => node.layer === layer).length,
    })),
    hotspots: architecture.modules
      .filter((node) => ["src/install.ts", "src/tools/controller.ts", "src/application/surface.ts", "src/tools/application_tools.ts", "src/application/http.ts", "src/deployment/launch.ts"].includes(node.file))
      .map((node) => ({ file: node.file, layer: node.layer, loc: node.loc, bytes: node.bytes, fanOut: node.fanOut, fanIn: node.fanIn })),
    topFanOut: [...architecture.modules].sort((a, b) => b.fanOut - a.fanOut).slice(0, 20).map((node) => ({ file: node.file, layer: node.layer, fanOut: node.fanOut })),
    topFanIn: [...architecture.modules].sort((a, b) => b.fanIn - a.fanIn).slice(0, 20).map((node) => ({ file: node.file, layer: node.layer, fanIn: node.fanIn })),
    layerEdges: architecture.layerEdges,
    forbiddenLayerEdges: architecture.forbiddenEdges.map((edge) => ({ edge: `${edge.fromLayer}->${edge.toLayer}`, count: edge.count })),
    cycles: architecture.stronglyConnectedComponents,
    directoryEdges: architecture.directoryEdges.slice(0, 80),
    baseline,
  };
  return `${JSON.stringify(payload, null, 2)}\n`;
}
