/**
 * R3-A0 §3/§4/§5 — THE FIXTURE FILE CONTENTS.
 *
 * The fixture SOURCES live here as data, and `construct-fixtures.mjs` writes them to disk and records a
 * content digest. Two reasons for the split:
 *
 *   · §5 requires each fixture revision to carry a `content digest`, and a digest is only meaningful if the
 *     bytes are produced by ONE reviewable artifact rather than by hand-editing files in place;
 *   · §2.5 freezes the lifecycle `DESIGN → FREEZE revision → QUALIFY frozen revision`. A revision that is
 *     written from this module cannot be quietly edited in place; changing it produces a NEW revision with a
 *     NEW digest, which is exactly the rule.
 *
 * CONSTRUCTION BASIS (§3). Both families were designed from MECHANISM requirements — what an atomic
 * transaction owes its caller, and what a versioned migration owes a forward-compatible consumer — BEFORE
 * any qualification model ran. No evaluation-model failure list was consulted. `constructionModel` is null.
 *
 * PLAIN JAVASCRIPT (`.mjs`).
 */

/* ================================================================ F-A: atomic transaction */

/**
 * F-A's starting point (H0). It commits the pre-paid mistake deliberately: it walks the operations and
 * applies each as it arrives, so it validates nothing, checks nothing, and has already mutated the caller's
 * store before it can discover that a later operation is unusable.
 */
export const FA_SOURCE_H0 = [
  '/**',
  ' * F-A — ATOMIC TRANSACTION APPLICATION (starting point H0).',
  ' *',
  ' * The store is the CALLER\'S object: the caller keeps using it, so a transaction that fails part-way',
  ' * through has already changed state the caller still holds.',
  ' *',
  ' * This implementation takes the obvious first move — walk the operations and apply each one as it',
  ' * arrives — and therefore:',
  ' *',
  ' *   · validates nothing before mutating;',
  ' *   · leaves a partial effect behind when a later operation is unusable;',
  ' *   · re-applies a transaction it has already applied;',
  ' *   · lets a balance go negative.',
  ' */',
  '',
  'export class LedgerError extends Error {',
  '  /**',
  '   * @param {string} code a stable, machine-readable failure code',
  '   * @param {string} message a human-readable explanation',
  '   */',
  '  constructor(code, message) {',
  '    super(message);',
  '    this.name = "LedgerError";',
  '    this.code = code;',
  '  }',
  '}',
  '',
  '/**',
  ' * Apply ONE transaction to the store.',
  ' *',
  ' * @param {{ accounts: Record<string, { balance: number }>, applied: Record<string, boolean> }} store',
  ' *   the CALLER\'S store; the caller keeps using the same object',
  ' * @param {{ id: string, operations: ReadonlyArray<{ kind: string, account: string, amount: number }> }} txn',
  ' * @returns the store',
  ' */',
  'export function applyTransaction(store, txn) {',
  '  for (const operation of txn.operations) {',
  '    const account = store.accounts[operation.account];',
  '    if (operation.kind === "credit") {',
  '      account.balance += operation.amount;',
  '    } else {',
  '      account.balance -= operation.amount;',
  '    }',
  '  }',
  '  store.applied[txn.id] = true;',
  '  return store;',
  '}',
  '',
].join('\n');

/**
 * F-A's VISIBLE oracle. It states the broad contract and exercises the ordinary path, so the worker can
 * iterate — and it deliberately does NOT enumerate the hidden classes, so the worker must reason about what
 * an atomic application owes its caller rather than reading the answers off the test file.
 */
export const FA_VISIBLE_ORACLE = [
  'import assert from "node:assert/strict";',
  'import { applyTransaction } from "../src/ledger.mjs";',
  '',
  'const fresh = () => ({ accounts: { a: { balance: 10 }, b: { balance: 5 } }, applied: {} });',
  '',
  '// An ordinary transaction applies and records itself.',
  '{',
  '  const store = fresh();',
  '  applyTransaction(store, { id: "t1", operations: [{ kind: "credit", account: "a", amount: 4 }] });',
  '  assert.equal(store.accounts.a.balance, 14, "a credit must be applied");',
  '  assert.equal(store.applied.t1, true, "an applied transaction must be recorded");',
  '}',
  '',
  '// A debit within the balance applies.',
  '{',
  '  const store = fresh();',
  '  applyTransaction(store, { id: "t2", operations: [{ kind: "debit", account: "a", amount: 3 }] });',
  '  assert.equal(store.accounts.a.balance, 7, "a covered debit must be applied");',
  '}',
  '',
  '// An unusable operation must not leave the caller\'s store changed.',
  '{',
  '  const store = fresh();',
  '  const before = JSON.stringify(store);',
  '  let threw = false;',
  '  try {',
  '    applyTransaction(store, { id: "t3", operations: [{ kind: "credit", account: "a", amount: 4 }, { kind: "credit", account: "missing", amount: 1 }] });',
  '  } catch {',
  '    threw = true;',
  '  }',
  '  assert.equal(threw, true, "a transaction naming an unknown account must be refused");',
  '  assert.equal(JSON.stringify(store), before, "a refused transaction must leave the store untouched");',
  '}',
  '',
  'process.stdout.write("ok" + String.fromCharCode(10));',
  '',
].join('\n');

/**
 * F-A's HIDDEN oracle — the authoritative, per-class judgement. Never copied into a world.
 *
 * Each case is judged in isolation against a FRESH store, and for a rejection the store is compared
 * byte-for-byte against its pre-call canonical form, so "atomic" is a mechanical fact rather than a claim.
 */
export const FA_ACCEPTANCE = [
  '/**',
  ' * F-A — THE HIDDEN ACCEPTANCE. Never copied into a worker\'s world.',
  ' *',
  ' * One case per declared failure class (some classes carry two). `judgeCase` gives the candidate a FRESH',
  ' * store, so one case cannot leak state into the next, and for a rejection it compares the store against its',
  ' * canonical form before the call.',
  ' */',
  '',
  'export const FA_CLASSES = Object.freeze([',
  '  Object.freeze({ id: "FA1", invariant: "atomic-rollback-on-reject", description: "an unusable operation anywhere in the batch leaves the caller\\u2019s store byte-identical" }),',
  '  Object.freeze({ id: "FA2", invariant: "validate-later-operation", description: "an operation AFTER a valid one is validated before the valid one has any effect" }),',
  '  Object.freeze({ id: "FA3", invariant: "idempotent-retry", description: "re-applying a transaction the store already applied is a no-op" }),',
  '  Object.freeze({ id: "FA4", invariant: "intra-transaction-order", description: "a debit covered by an EARLIER credit in the same transaction is allowed" }),',
  '  Object.freeze({ id: "FA5", invariant: "insufficient-funds-rejected", description: "a debit that would overdraw is refused, leaving the store untouched" }),',
  '  Object.freeze({ id: "FA6", invariant: "unrelated-state-preserved", description: "a successful transaction leaves every other account and applied id exactly as it was" }),',
  ']);',
  '',
  'const store = (accounts, applied = {}) => ({ accounts: Object.fromEntries(Object.entries(accounts).map(([id, balance]) => [id, { balance }])), applied: { ...applied } });',
  '',
  'export const FA_CASES = Object.freeze([',
  '  // FA1: an unknown account appears LAST, after a perfectly good credit.',
  '  Object.freeze({ id: "fa1a", failureClass: "FA1", expect: "reject", store: store({ a: 10, b: 5 }), txn: { id: "x1", operations: [{ kind: "credit", account: "a", amount: 4 }, { kind: "credit", account: "ghost", amount: 1 }] } }),',
  '  // FA1: a non-integer amount appears LAST.',
  '  Object.freeze({ id: "fa1b", failureClass: "FA1", expect: "reject", store: store({ a: 10 }), txn: { id: "x2", operations: [{ kind: "credit", account: "a", amount: 2 }, { kind: "credit", account: "a", amount: 1.5 }] } }),',
  '  // FA2: ops[0] is valid, ops[1] has amount 0. Nothing may be applied.',
  '  Object.freeze({ id: "fa2a", failureClass: "FA2", expect: "reject", store: store({ a: 10, b: 5 }), txn: { id: "x3", operations: [{ kind: "credit", account: "a", amount: 7 }, { kind: "debit", account: "b", amount: 0 }] } }),',
  '  // FA3: the store has ALREADY applied this id; the retry must change nothing.',
  '  Object.freeze({ id: "fa3a", failureClass: "FA3", expect: "accept", store: store({ a: 10, b: 5 }, { x4: true }), txn: { id: "x4", operations: [{ kind: "credit", account: "a", amount: 99 }] }, after: store({ a: 10, b: 5 }, { x4: true }) }),',
  '  // FA4: the debit is only covered by the credit that comes BEFORE it.',
  '  Object.freeze({ id: "fa4a", failureClass: "FA4", expect: "accept", store: store({ a: 0, b: 5 }), txn: { id: "x5", operations: [{ kind: "credit", account: "a", amount: 8 }, { kind: "debit", account: "a", amount: 6 }] }, after: store({ a: 2, b: 5 }, { x5: true }) }),',
  '  // FA4: the same net effect, but the debit comes FIRST, so it overdraws mid-sequence and must be refused.',
  '  Object.freeze({ id: "fa4b", failureClass: "FA4", expect: "reject", store: store({ a: 0, b: 5 }), txn: { id: "x6", operations: [{ kind: "debit", account: "a", amount: 6 }, { kind: "credit", account: "a", amount: 8 }] } }),',
  '  // FA5: a plain overdraw.',
  '  Object.freeze({ id: "fa5a", failureClass: "FA5", expect: "reject", store: store({ a: 3, b: 5 }), txn: { id: "x7", operations: [{ kind: "debit", account: "a", amount: 4 }] } }),',
  '  // FA6: a successful transaction must not disturb b, nor another applied id.',
  '  Object.freeze({ id: "fa6a", failureClass: "FA6", expect: "accept", store: store({ a: 10, b: 5 }, { old: true }), txn: { id: "x8", operations: [{ kind: "debit", account: "a", amount: 2 }] }, after: store({ a: 8, b: 5 }, { old: true, x8: true }) }),',
  ']);',
  '',
  'export function canonical(value) {',
  '  if (Array.isArray(value)) return `[${value.map(canonical).join(",")}]`;',
  '  if (value !== null && typeof value === "object") return `{${Object.keys(value).sort().map((key) => `${JSON.stringify(key)}:${canonical(value[key])}`).join(",")}}`;',
  '  return JSON.stringify(value) ?? "null";',
  '}',
  '',
  '/** Judge ONE case against the candidate. The store is compared canonically, so key order cannot matter. */',
  'export function judgeCase(applyTransaction, testCase) {',
  '  const target = structuredClone(testCase.store);',
  '  const before = canonical(target);',
  '  let outcome;',
  '  try {',
  '    applyTransaction(target, structuredClone(testCase.txn));',
  '    outcome = { kind: "returned" };',
  '  } catch (error) {',
  '    outcome = { kind: "threw", code: error?.code ?? error?.name ?? "Error" };',
  '  }',
  '  const base = { id: testCase.id, failureClass: testCase.failureClass, invariant: FA_CLASSES.find((entry) => entry.id === testCase.failureClass)?.invariant ?? "UNKNOWN" };',
  '  if (testCase.expect === "reject") {',
  '    if (outcome.kind === "returned") return { ...base, pass: false, failureClass_detail: "ACCEPTED_INVALID_TRANSACTION", detail: canonical(target).slice(0, 120) };',
  '    if (canonical(target) !== before) return { ...base, pass: false, failureClass_detail: "MUTATED_STORE_BEFORE_REJECTING", detail: `${before} -> ${canonical(target)}` };',
  '    return { ...base, pass: true, failureClass_detail: null, detail: "" };',
  '  }',
  '  if (outcome.kind === "threw") return { ...base, pass: false, failureClass_detail: "REJECTED_BUT_SHOULD_ACCEPT", detail: outcome.code };',
  '  if (canonical(target) !== canonical(testCase.after)) return { ...base, pass: false, failureClass_detail: "WRONG_STORE", detail: `expected ${canonical(testCase.after).slice(0, 100)}, got ${canonical(target).slice(0, 100)}` };',
  '  return { ...base, pass: true, failureClass_detail: null, detail: "" };',
  '}',
  '',
  'export function runCases(applyTransaction, cases) {',
  '  const results = cases.map((testCase) => judgeCase(applyTransaction, testCase));',
  '  return { results, passed: results.filter((result) => result.pass).length, total: results.length };',
  '}',
  '',
].join('\n');

export const FA_PACKAGE_JSON = `${JSON.stringify({ name: 'r3a-f-a-atomic-transaction', private: true, type: 'module', scripts: { test: 'node test/check.js' } }, null, 2)}\n`;

export const FA_README = [
  '# F-A — atomic transaction application',
  '',
  '`applyTransaction(store, txn)` applies ONE transaction to a caller-owned store.',
  '',
  '## The store',
  '',
  '```js',
  '{ accounts: { [accountId]: { balance: number } }, applied: { [txnId]: true } }',
  '```',
  '',
  '## The transaction',
  '',
  '```js',
  '{ id: string, operations: [{ kind: "credit" | "debit", account: string, amount: number }] }',
  '```',
  '',
  '## What the contract requires',
  '',
  '· `applyTransaction` returns the store.',
  '· An unusable transaction is REFUSED by throwing an error with a `code`, and a refused transaction must',
  '  leave the caller\'s store exactly as it was.',
  '· A transaction the store has already applied is a no-op.',
  '· A debit may not take an account below zero.',
  '· Accounts the transaction does not name must be left alone.',
  '',
  '## Running the checks',
  '',
  '```',
  'node test/check.js',
  '```',
  '',
  'The visible checks cover the ordinary path. They are not the whole contract.',
  '',
].join('\n');

/* ================================================================ F-B: versioned migration */

/**
 * F-B's starting point (H0). It builds the v2 shape from the fields it knows about, so it silently discards
 * every field it does not know, repairs values the contract requires to be refused, and accepts a version it
 * has never seen.
 */
export const FB_SOURCE_H0 = [
  '/**',
  ' * F-B — VERSIONED DOCUMENT MIGRATION (starting point H0).',
  ' *',
  ' * The document is a CONSUMER\'S configuration: other services hold copies of it, and a migration that',
  ' * silently drops a field it does not recognize breaks forward compatibility without saying so.',
  ' *',
  ' * This implementation builds the new shape from the fields it knows about, and therefore:',
  ' *',
  ' *   · discards every field the contract does not define;',
  ' *   · replaces a present-but-unusable value with a default instead of refusing it;',
  ' *   · accepts a version it has never seen.',
  ' */',
  '',
  'export class ConfigError extends Error {',
  '  /**',
  '   * @param {string} code a stable, machine-readable failure code',
  '   * @param {string} message a human-readable explanation',
  '   */',
  '  constructor(code, message) {',
  '    super(message);',
  '    this.name = "ConfigError";',
  '    this.code = code;',
  '  }',
  '}',
  '',
  '/**',
  ' * Migrate ONE document to the current shape.',
  ' *',
  ' * @param {Record<string, unknown>} input the caller\'s document; the caller keeps using the same object',
  ' * @returns {Record<string, unknown>} the migrated document',
  ' */',
  'export function migrateDocument(input) {',
  '  return {',
  '    version: 2,',
  '    retryCount: input.retry_count ?? input.retryCount ?? 3,',
  '    timeoutMs: input.timeoutMs ?? input.timeout_ms ?? 3000,',
  '  };',
  '}',
  '',
].join('\n');

export const FB_VISIBLE_ORACLE = [
  'import assert from "node:assert/strict";',
  'import { migrateDocument } from "../src/config.mjs";',
  '',
  '// A v1 document gains the current shape.',
  '{',
  '  const out = migrateDocument({ version: 1, retry_count: 5 });',
  '  assert.equal(out.version, 2, "the migrated document must be the current version");',
  '  assert.equal(out.retryCount, 5, "retry_count must be carried across");',
  '  assert.equal(out.timeoutMs, 3000, "an absent timeout must take the default");',
  '}',
  '',
  '// A field the contract does not define survives the migration.',
  '{',
  '  const out = migrateDocument({ version: 1, retry_count: 1, featureFlag: true });',
  '  assert.equal(out.featureFlag, true, "a field the contract does not define must be preserved");',
  '}',
  '',
  '// The caller\'s document is not modified.',
  '{',
  '  const input = { version: 1, retry_count: 2 };',
  '  const before = JSON.stringify(input);',
  '  migrateDocument(input);',
  '  assert.equal(JSON.stringify(input), before, "migrateDocument must not mutate its argument");',
  '}',
  '',
  'process.stdout.write("ok" + String.fromCharCode(10));',
  '',
].join('\n');

export const FB_ACCEPTANCE = [
  '/**',
  ' * F-B — THE HIDDEN ACCEPTANCE. Never copied into a worker\'s world.',
  ' *',
  ' * One case per declared failure class (some classes carry two). Every case deep-clones its input, so a',
  ' * mutation performed by the candidate cannot leak into the next case, and a rejection is checked for',
  ' * having left the input untouched.',
  ' */',
  '',
  'export const FB_CLASSES = Object.freeze([',
  '  Object.freeze({ id: "FB1", invariant: "unknown-field-preserved", description: "a field the contract does not define survives the migration verbatim" }),',
  '  Object.freeze({ id: "FB2", invariant: "default-only-when-absent", description: "the default is inserted ONLY when the key is absent" }),',
  '  Object.freeze({ id: "FB3", invariant: "v1-rename-applied", description: "the v1 spelling is renamed to the v2 name and the old spelling is gone" }),',
  '  Object.freeze({ id: "FB4", invariant: "future-version-rejected", description: "a version the contract does not define is refused rather than guessed at" }),',
  '  Object.freeze({ id: "FB5", invariant: "v2-round-trip-stable", description: "a current-version document migrates to an equal document" }),',
  '  Object.freeze({ id: "FB6", invariant: "malformed-nested-rejected", description: "a nested value of the wrong shape is refused" }),',
  '  Object.freeze({ id: "FB7", invariant: "present-but-unusable-refused", description: "an explicitly present but unusable value is refused, not repaired into a default" }),',
  ']);',
  '',
  'export function canonical(value) {',
  '  if (Array.isArray(value)) return `[${value.map(canonical).join(",")}]`;',
  '  if (value !== null && typeof value === "object") return `{${Object.keys(value).sort().map((key) => `${JSON.stringify(key)}:${canonical(value[key])}`).join(",")}}`;',
  '  return JSON.stringify(value) ?? "null";',
  '}',
  '',
  'export const FB_CASES = Object.freeze([',
  '  // FB1: a field the contract does not define, including a nested one.',
  '  Object.freeze({ id: "fb1a", failureClass: "FB1", expect: "accept", input: { version: 1, retry_count: 2, featureFlag: true, nested: { keep: [1, 2] } }, after: { version: 2, retryCount: 2, timeoutMs: 3000, featureFlag: true, nested: { keep: [1, 2] } } }),',
  '  // FB2: the key is absent, so the default is inserted.',
  '  Object.freeze({ id: "fb2a", failureClass: "FB2", expect: "accept", input: { version: 2, retryCount: 4 }, after: { version: 2, retryCount: 4, timeoutMs: 3000 } }),',
  '  // FB3: the v1 spelling is renamed and the old spelling does not survive.',
  '  Object.freeze({ id: "fb3a", failureClass: "FB3", expect: "accept", input: { version: 1, retry_count: 7 }, after: { version: 2, retryCount: 7, timeoutMs: 3000 } }),',
  '  // FB4: a version the contract does not define.',
  '  Object.freeze({ id: "fb4a", failureClass: "FB4", expect: "reject", input: { version: 3, retryCount: 1 } }),',
  '  // FB5: a current-version document is already current.',
  '  Object.freeze({ id: "fb5a", failureClass: "FB5", expect: "accept", input: { version: 2, retryCount: 9, timeoutMs: 1200 }, after: { version: 2, retryCount: 9, timeoutMs: 1200 } }),',
  '  // FB6: a nested value of the wrong shape.',
  '  Object.freeze({ id: "fb6a", failureClass: "FB6", expect: "reject", input: { version: 2, retryCount: 1, nested: "not-an-object" } }),',
  '  // FB7: the key is PRESENT and unusable — it must be refused, not repaired.',
  '  Object.freeze({ id: "fb7a", failureClass: "FB7", expect: "reject", input: { version: 2, retryCount: 1, timeoutMs: null } }),',
  '  Object.freeze({ id: "fb7b", failureClass: "FB7", expect: "reject", input: { version: 2, retryCount: 1, timeoutMs: -5 } }),',
  ']);',
  '',
  '/** Judge ONE case. A rejection is checked for having left the INPUT untouched. */',
  'export function judgeCase(migrateDocument, testCase) {',
  '  const input = structuredClone(testCase.input);',
  '  const before = canonical(input);',
  '  let outcome;',
  '  try {',
  '    outcome = { kind: "returned", value: migrateDocument(input) };',
  '  } catch (error) {',
  '    outcome = { kind: "threw", code: error?.code ?? error?.name ?? "Error" };',
  '  }',
  '  const base = { id: testCase.id, failureClass: testCase.failureClass, invariant: FB_CLASSES.find((entry) => entry.id === testCase.failureClass)?.invariant ?? "UNKNOWN" };',
  '  if (canonical(input) !== before) return { ...base, pass: false, failureClass_detail: "MUTATED_INPUT", detail: `${before} -> ${canonical(input)}` };',
  '  if (testCase.expect === "reject") {',
  '    if (outcome.kind === "returned") return { ...base, pass: false, failureClass_detail: "ACCEPTED_INVALID_DOCUMENT", detail: canonical(outcome.value).slice(0, 120) };',
  '    return { ...base, pass: true, failureClass_detail: null, detail: "" };',
  '  }',
  '  if (outcome.kind === "threw") return { ...base, pass: false, failureClass_detail: "REJECTED_BUT_SHOULD_ACCEPT", detail: outcome.code };',
  '  if (canonical(outcome.value) !== canonical(testCase.after)) return { ...base, pass: false, failureClass_detail: "WRONG_DOCUMENT", detail: `expected ${canonical(testCase.after).slice(0, 110)}, got ${canonical(outcome.value).slice(0, 110)}` };',
  '  return { ...base, pass: true, failureClass_detail: null, detail: "" };',
  '}',
  '',
  'export function runCases(migrateDocument, cases) {',
  '  const results = cases.map((testCase) => judgeCase(migrateDocument, testCase));',
  '  return { results, passed: results.filter((result) => result.pass).length, total: results.length };',
  '}',
  '',
].join('\n');

export const FB_PACKAGE_JSON = `${JSON.stringify({ name: 'r3a-f-b-versioned-migration', private: true, type: 'module', scripts: { test: 'node test/check.js' } }, null, 2)}\n`;

export const FB_README = [
  '# F-B — versioned document migration',
  '',
  '`migrateDocument(input)` migrates ONE configuration document to the current shape.',
  '',
  '## What the contract requires',
  '',
  '· It returns a NEW document. It never modifies the document it was given.',
  '· `version` must be `1` or `2`. Any other version is refused.',
  '· A version-1 document uses the old spelling `retry_count`; the migrated document uses `retryCount`, and',
  '  the old spelling does not survive.',
  '· `timeoutMs` (or `timeout_ms` in version 1) takes the default `3000` ONLY when the key is absent.',
  '· A field the contract does not define is preserved verbatim.',
  '· A nested value, if present, must be an object.',
  '· An unusable value is refused by throwing an error with a `code` — it is never repaired into a default.',
  '',
  '## Running the checks',
  '',
  '```',
  'node test/check.js',
  '```',
  '',
  'The visible checks cover the ordinary path. They are not the whole contract.',
  '',
].join('\n');

/* ================================================================ the fixture registry */

/**
 * §4/§5: the two families, as data. `contentFiles` is what `construct-fixtures.mjs` writes; the digest is
 * computed over those bytes, so a hand-edit of a fixture file changes the digest and therefore invalidates
 * its qualification record.
 */
export const FIXTURE_SPECS = Object.freeze([
  Object.freeze({
    fixtureId: 'r3a-f-a-atomic-transaction',
    fixtureRevision: 1,
    mechanismFamily: 'F-A transactional / atomic state update',
    name: 'F_A_ATOMIC_TRANSACTION',
    sourceFile: 'src/ledger.mjs',
    exportName: 'applyTransaction',
    acceptanceFile: 'acceptance.mjs',
    taskObjective: 'finish applyTransaction so it applies a transaction to the caller\'s store correctly',
    projectGoal: 'make a batch of account updates land all-or-nothing',
    requirements: Object.freeze([
      'applyTransaction must apply a transaction to the caller\'s store',
      'the store must be correct for every transaction the ledger admits',
    ]),
    hiddenNeedles: Object.freeze(['THE HIDDEN ACCEPTANCE', 'FA_CLASSES', 'judgeCase']),
    files: Object.freeze({
      'README.md': FA_README,
      'package.json': FA_PACKAGE_JSON,
      'src/ledger.mjs': FA_SOURCE_H0,
      'test/check.js': FA_VISIBLE_ORACLE,
      'acceptance.mjs': FA_ACCEPTANCE,
    }),
    /** §6: the declared independence structure, audited in `independence-audit.json`. */
    classStructure: Object.freeze({
      independent: Object.freeze(['FA1', 'FA3', 'FA4', 'FA5', 'FA6']),
      partiallyCoupled: Object.freeze([Object.freeze({ classes: Object.freeze(['FA1', 'FA2']), why: 'both concern validation preceding effect; FA2 isolates the case where the unusable operation comes AFTER a valid one' })]),
      derived: Object.freeze([]),
    }),
  }),
  Object.freeze({
    fixtureId: 'r3a-f-b-versioned-migration',
    fixtureRevision: 1,
    mechanismFamily: 'F-B versioned schema / API compatibility',
    name: 'F_B_VERSIONED_MIGRATION',
    sourceFile: 'src/config.mjs',
    exportName: 'migrateDocument',
    acceptanceFile: 'acceptance.mjs',
    taskObjective: 'finish migrateDocument so it migrates a versioned configuration document correctly',
    projectGoal: 'move consumers onto the current configuration shape without breaking the ones that follow',
    requirements: Object.freeze([
      'migrateDocument must migrate a document to the current shape',
      'the migration must be correct for every document the contract admits',
    ]),
    hiddenNeedles: Object.freeze(['THE HIDDEN ACCEPTANCE', 'FB_CLASSES', 'judgeCase']),
    files: Object.freeze({
      'README.md': FB_README,
      'package.json': FB_PACKAGE_JSON,
      'src/config.mjs': FB_SOURCE_H0,
      'test/check.js': FB_VISIBLE_ORACLE,
      'acceptance.mjs': FB_ACCEPTANCE,
    }),
    classStructure: Object.freeze({
      independent: Object.freeze(['FB1', 'FB3', 'FB4', 'FB5', 'FB6']),
      partiallyCoupled: Object.freeze([Object.freeze({ classes: Object.freeze(['FB2', 'FB7']), why: 'both concern the default policy; FB2 is the ABSENT key, FB7 is the PRESENT-but-unusable value, and the contract treats them oppositely' })]),
      derived: Object.freeze([]),
    }),
  }),
]);
