/** R3-L0C-F contract module type declarations (harness-only). */
export declare const REPO_ROOT: string;
export declare const BASELINE_COMMIT: string;
export declare const STAGE_BRANCH: string;
export declare const STAGE_EVIDENCE_PATH: string;
export declare const FROZEN_STAGES: readonly string[];
export declare const PROTOCOL_DEVIATION: any;
export declare const FAIL_STOP_STATES: readonly any[];
export declare const FAIL_STOP_TRANSITIONS: Readonly<Record<string, readonly string[]>>;
export declare const TERMINAL_PRESERVED_STATES: readonly string[];
export declare const LAUNCH_LAW: any;
export declare const EXPOSURE_INTENT: any;
export declare const FAILURE_CLASSES: any;
export declare const CLASSIFICATION_LAW: any;
export declare const JOURNAL_FIELDS: readonly string[];
export declare const JOURNAL_PROTOCOL: any;
export declare const JOURNAL_EVENT_TYPES: readonly string[];
export declare const CLOSURE_PARTS: readonly any[];
export declare const CLOSURE_FILES: Readonly<Record<string, readonly string[]>>;
export declare const CLOSURE_SELF_EXCLUSIONS: readonly string[];
export declare const CLOSURE_LAW: any;
export declare const BOUNDARY_EXPECTATIONS: any;
export declare const PREFLIGHT_LAW: any;
export declare const SUBSTITUTABILITY_RECORDS: readonly string[];
export declare const HISTORY_READING_DISTINCTIONS: any;
export declare const README_HISTORY_INSTRUCTION: any;
export declare const BEHAVIORAL_DESIGN: any;
export declare const VERDICT_ADMISSION_PRECONDITIONS: readonly string[];
export declare const INDEPENDENCE_UNIT: any;
export declare const CAPITAL_STAGES: readonly string[];
export declare const ANALYSIS_READING_RULES: any;
export declare const ON_VALIDITY_FAILURE: any;
export declare const FAIL_STOP_POLICY_BOUNDARY: any;
export declare const COMMIT_STRUCTURE: readonly string[];
export declare const COMMIT_ORDER_LAW: any;
export declare const CRASH_MATRIX_CASES: readonly any[];
export declare const CRASH_MATRIX_REQUIREMENTS: readonly string[];
export declare const HEALTHY_CONTROL_REQUIREMENT: any;
export declare const PRESERVATION_REQUIREMENTS: readonly string[];
export declare const PRESERVATION_LAW: any;
export declare const CONTAINMENT_REQUIREMENTS: readonly string[];
export declare const CONTAINMENT_LAW: any;
export declare const FINAL_VERDICTS: Readonly<Record<string, readonly string[]>>;
export declare const STAGE_STOP: any;
export declare function contractSummary(): any;
export declare const NL: string;
