#!/usr/bin/env node
/**
 * RS-1 §3/§11/§15 — render the human-readable audit documents from the recorded JSON.
 *
 * The tables are GENERATED from `branches-before.json` / `branch-classification.json` rather than
 * transcribed, so the document and the machine record cannot disagree. Prose is added by hand in the
 * surrounding sections; every per-branch cell here is a recorded fact.
 *
 *   node scripts/repository/branch-report.mjs --mode before|plan|after
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { join } from "node:path";

const argv = process.argv.slice(2);
const flag = (name, fallback) => {
  const index = argv.indexOf(name);
  return index >= 0 && argv[index + 1] !== undefined ? argv[index + 1] : fallback;
};
const REPO = process.cwd();
const MODE = flag("--mode", "before");
const readJson = (path) => JSON.parse(readFileSync(join(REPO, path), "utf8"));

/** The four confidence batches of §13, assigned from the classification and the family. */
const DELETABLE_CLASSES = [
  "A_MERGED_ANCESTOR",
  "B_MERGED_PR_EQUIVALENT",
  "C_SUPERSEDED_HISTORY",
  "F_ABANDONED_UNMERGED",
];

function batchOf(branch) {
  if (!DELETABLE_CLASSES.includes(branch.classification)) return 0;
  if (branch.classification === "A_MERGED_ANCESTOR" || branch.classification === "B_MERGED_PR_EQUIVALENT") {
    return /closure|checkpoint/.test(branch.name) ? 2 : 1;
  }
  if (branch.classification === "C_SUPERSEDED_HISTORY") return 3;
  return 4;
}
const BATCH_NAMES = {
  0: "not deleted (protected or retained)",
  1: "Batch 1 — merged ancestors and merged-PR branches",
  2: "Batch 2 — checkpoint / closure branches",
  3: "Batch 3 — superseded historical branches",
  4: "Batch 4 — abandoned unique-history branches",
};

const cell = (value) => String(value).replace(/\|/gu, "\\|");

if (MODE === "before") {
  const inv = readJson(join("repository-audit", "branches-before.json"));
  const lines = [
    "# RS-1 — remote branch inventory (BEFORE)",
    "",
    "Generated by `node scripts/repository/branch-report.mjs --mode before` from",
    "`repository-audit/branches-before.json`. Every field is read from Git reachability or the GitHub",
    "PR API; **none is inferred from a branch name** (§1/§5).",
    "",
    "```text",
    `captured at        ${inv.capturedAt}`,
    `repository         ${inv.repository}`,
    `canonical main     ${inv.mainSha}`,
    `canonical tree     ${inv.mainTree}`,
    `remote branches    ${String(inv.remoteBranchCount)}`,
    "```",
    "",
    "Column meanings: *ahead* = commits reachable from the tip but not from main; *behind* = commits",
    "reachable from main but not from the tip; *anc* = `git merge-base --is-ancestor <tip> origin/main`.",
    "",
    "| branch | tip | tip date | ahead | behind | anc | unique | PRs | tip subject |",
    "| --- | --- | --- | --- | --- | --- | --- | --- | --- |",
  ];
  for (const b of inv.branches) {
    const prs = b.pullRequests.map((pr) => `#${String(pr.number)}:${pr.state}${pr.tipMatchesHead ? "" : " (pre-follow-up)"}`).join(" ") || "—";
    lines.push(
      `| \`${cell(b.name)}\` | \`${b.tipSha.slice(0, 12)}\` | ${b.tipDate.slice(0, 10)} | ${String(b.aheadOfMain)} | ${String(b.behindMain)} | ${b.tipIsAncestorOfMain ? "yes" : "no"} | ${String(b.uniqueCommitCount)} | ${prs} | ${cell(b.tipSubject.slice(0, 60))} |`,
    );
  }
  lines.push("");
  mkdirSync(join(REPO, "docs", "engineering", "repository"), { recursive: true });
  writeFileSync(join(REPO, "docs", "engineering", "repository", "BRANCH-INVENTORY-BEFORE.md"), `${lines.join("\n")}\n`);
  process.stdout.write(`rendered BRANCH-INVENTORY-BEFORE.md (${String(inv.branches.length)} branches)\n`);
}

if (MODE === "plan") {
  const inv = readJson(join("repository-audit", "branches-before.json"));
  const cls = readJson(join("repository-audit", "branch-classification.json"));
  const byName = new Map(inv.branches.map((b) => [b.name, b]));
  const counts = cls.counts;
  const batchCounts = {};
  for (const branch of cls.branches) {
    const b = batchOf(branch);
    batchCounts[b] = (batchCounts[b] ?? 0) + 1;
  }
  const lines = [
    "# RS-1 — branch cleanup plan",
    "",
    "Produced AFTER the per-branch audit and BEFORE any deletion (§11). The table is generated from",
    "`repository-audit/branch-classification.json`, so it cannot disagree with the machine record.",
    "",
    "## Summary",
    "",
    "```text",
    `total remote branches      ${String(cls.total)}`,
    `classified A (merged)      ${String(counts.A_MERGED_ANCESTOR ?? 0)}`,
    `classified B (PR-equivalent) ${String(counts.B_MERGED_PR_EQUIVALENT ?? 0)}`,
    `classified C (superseded)  ${String(counts.C_SUPERSEDED_HISTORY ?? 0)}`,
    `classified F (abandoned)   ${String(counts.F_ABANDONED_UNMERGED ?? 0)}`,
    `classified E (active)      ${String(counts.E_ACTIVE ?? 0)}`,
    `classified G (review)      ${String(counts.G_REVIEW_REQUIRED ?? 0)}`,
    `protected (main)           ${String(counts.P_PROTECTED_MAIN ?? 0)}`,
    `safe-delete                ${String(cls.deletable)}`,
    `tag-then-delete            ${String((counts.D_HISTORICAL_MILESTONE ?? 0))}`,
    `active (retained)          ${String(counts.E_ACTIVE ?? 0)}`,
    `review-required (retained) ${String(counts.G_REVIEW_REQUIRED ?? 0)}`,
    "```",
    "",
    "## Batches (§13)",
    "",
    ...Object.entries(batchCounts)
      .filter(([key]) => Number(key) > 0)
      .sort()
      .map(([key, value]) => `- **${BATCH_NAMES[key]}** — ${String(value)} branch(es)`),
    "",
    "## Plan table",
    "",
    "| branch | classification | tip | ahead/behind | merged PR | unique | preservation action | delete? | reason |",
    "| --- | --- | --- | --- | --- | --- | --- | --- | --- |",
  ];
  for (const branch of [...cls.branches].sort((a, b) => batchOf(a) - batchOf(b) || a.name.localeCompare(b.name))) {
    const inv_ = byName.get(branch.name);
    const merged = branch.mergedPullRequests.map((pr) => `#${String(pr.number)}→${String(pr.mergeCommit).slice(0, 8)}`).join(" ") || "—";
    const deletable = DELETABLE_CLASSES.includes(branch.classification);
    lines.push(
      `| \`${cell(branch.name)}\` | ${branch.classification} | \`${branch.tipSha.slice(0, 12)}\` | ${String(inv_?.aheadOfMain ?? branch.aheadOfMain)}/${String(inv_?.behindMain ?? branch.behindMain)} | ${merged} | ${String(branch.uniqueCommitCount)} | ${cell(branch.preservationAction ?? "audit SHA record only")} | ${deletable ? "yes" : "no"} | ${cell(branch.basis.slice(0, 220))} |`,
    );
  }
  lines.push("");
  mkdirSync(join(REPO, "docs", "engineering", "repository"), { recursive: true });
  writeFileSync(join(REPO, "docs", "engineering", "repository", "BRANCH-CLEANUP-PLAN.md"), `${lines.join("\n")}\n`);
  process.stdout.write(`rendered BRANCH-CLEANUP-PLAN.md (${String(cls.branches.length)} rows)\n`);
}

if (MODE === "after") {
  const path = join("repository-audit", "branches-after.json");
  if (!existsSync(join(REPO, path))) {
    process.stderr.write(`missing ${path}: run the audit with --out repository-audit/branches-after.json\n`);
    process.exit(2);
  }
  const after = readJson(path);
  const before = readJson(join("repository-audit", "branches-before.json"));
  const cls = readJson(join("repository-audit", "branch-classification.json"));
  const deleted = cls.branches.filter((b) => !after.branches.some((a) => a.name === b.name));
  const retained = cls.branches.filter((b) => after.branches.some((a) => a.name === b.name));
  const lines = [
    "# RS-1 — remote branch inventory (AFTER)",
    "",
    "Generated by `node scripts/repository/branch-report.mjs --mode after` from",
    "`repository-audit/branches-after.json`.",
    "",
    "```text",
    `captured at        ${after.capturedAt}`,
    `canonical main     ${after.mainSha}`,
    `canonical tree     ${after.mainTree}`,
    `remote branches    ${String(after.remoteBranchCount)}  (before: ${String(before.remoteBranchCount)})`,
    `deleted            ${String(deleted.length)}`,
    `retained           ${String(retained.length)}`,
    "```",
    "",
    "## Mechanical invariants (§15)",
    "",
    "```text",
    `main SHA before == after   ${before.mainSha === after.mainSha ? "TRUE" : "FALSE"}   (${before.mainSha})`,
    `main tree before == after  ${before.mainTree === after.mainTree ? "TRUE" : "FALSE"}   (${before.mainTree})`,
    `all planned deletions gone ${String(deleted.length)} of ${String(cls.deletable)} assigned for deletion are absent`,
    `all retained refs present  ${String(retained.length)} retained, ${String(retained.filter((b) => !after.branches.some((a) => a.name === b.name)).length)} missing`,
    "```",
    "",
    "## Retained branches",
    "",
  ];
  if (retained.length === 0) lines.push("None: every non-main branch was classified deletable, so `main` is the only branch.", "");
  else {
    lines.push("| branch | classification | purpose |", "| --- | --- | --- |");
    for (const b of retained) lines.push(`| \`${cell(b.name)}\` | ${b.classification} | ${cell(b.purposeReview?.purpose ?? "see the cleanup plan")} |`);
    lines.push("");
  }
  lines.push("## Milestone tags created", "", "See `RS-1-DELIVERY.md` and the tag list in this document's sibling inventory.", "");
  mkdirSync(join(REPO, "docs", "engineering", "repository"), { recursive: true });
  writeFileSync(join(REPO, "docs", "engineering", "repository", "BRANCH-INVENTORY-AFTER.md"), `${lines.join("\n")}\n`);
  process.stdout.write(`rendered BRANCH-INVENTORY-AFTER.md (${String(after.branches.length)} branches, ${String(deleted.length)} deleted)\n`);
}
