/** R3-L0B contract module type declarations (harness-only, research evidence infrastructure). */
export declare const EXPERIMENT_VALIDITY_COMPONENTS: readonly any[];
export declare const COMPONENT_VERDICTS: { readonly PASS: string; readonly FAIL: string } & Readonly<Record<string, string>>;
export declare function experimentValidFrom(components: any): any;
export declare const BEHAVIORAL_CLAIM_ADMISSION: any;
export declare function admitBehavioralClaim(input: any): any;
export declare const VISIBILITY: { readonly WORKER_VISIBLE: string; readonly HOST_PRIVATE: string } & Readonly<Record<string, string>>;
export declare const EXPERIMENT_CONTAINMENT_ENVELOPE: any;
export declare function envelopeEntries(): readonly any[];
export declare function hostPrivateIds(): readonly string[];
export declare const EXPOSURE_CLASSES: { readonly CHECKOUT_EXPOSED: string; readonly ORACLE_EXPOSED: string; readonly SIBLING_TRAJECTORY_EXPOSED: string; readonly CONTROL_PLANE_EXPOSED: string; readonly OTHER: string } & Readonly<Record<string, string>>;
export declare const ACCESS_OPERATIONS: { readonly READ: string; readonly ENUMERATE: string; readonly IMPORT: string; readonly EXECUTE: string; readonly SEARCH: string } & Readonly<Record<string, string>>;
export declare const SPILLOVER_CLASSES: { readonly NO_TREATMENT_SPILLOVER: string; readonly TREATMENT_SPILLOVER_POSSIBLE: string; readonly TREATMENT_SPILLOVER_CONFIRMED: string; readonly UNKNOWN: string } & Readonly<Record<string, string>>;
export declare function adjudicateSpillover(input: any): any;
export declare const ORACLE_EXPOSURE_QUESTIONS: readonly any[];
export declare function adjudicateOracleExposure(input: any): any;
export declare const SESSION_LABELS: { readonly CLEAN: string; readonly CONTAMINATED_NON_ORACLE: string; readonly ORACLE_CONTAMINATED: string; readonly CROSS_TRAJECTORY_CONTAMINATED: string } & Readonly<Record<string, string>>;
export declare function labelSession(input: any): string;
export declare function labelBlock(sessionLabels: readonly string[]): any;
export declare const ROOT_CAUSE_LAYERS: { readonly PRODUCTION_RUNTIME_DESIGN: string; readonly RESEARCH_HARNESS_DIRECTORY_LAYOUT: string; readonly SECURITY_PROFILE_SCOPE: string } & Readonly<Record<string, string>>;
export declare const CONFIDENTIALITY_CLAIM_LAW: any;
export declare const CANARY_ROOTS: readonly any[];
export declare const CANARY_ATTEMPTS: readonly any[];
export declare const CANARY_VERDICTS: { readonly UNREACHABLE: string; readonly REACHABLE: string; readonly NOT_APPLICABLE: string } & Readonly<Record<string, string>>;
export declare function experimentContainmentFrom(probes: readonly any[]): any;
export declare const CONTAINMENT_MUTATIONS: readonly any[];
export declare const R3L0_EVIDENCE_CLASSES: any;
export declare const EXPERIMENT_LAWS: Readonly<Record<string, string>>;
export declare const RECONSTRUCTION_PRESSURE_REQUIREMENTS: readonly any[];
export declare const PRE_RULING_SCOPE: any;
export declare const RECONSTRUCTION_PRIMARY_OUTCOMES: readonly any[];
export declare const FUTURE_OUTCOME_SCOPE: any;
export declare const PRESERVED_COMMITS: readonly string[];
export declare const STAGE_EVIDENCE_PATH: string;
export declare const REPO_ROOT: string;
export declare function contractSummary(): any;
